"""Corrigiendo migraciones en PC escritorio

Revision ID: 088f20761db6
Revises: 209a0e5cc9a4
Create Date: 2025-02-03 12:15:52.784407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '088f20761db6'
down_revision = '209a0e5cc9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=10), nullable=True))
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
