"""Creación del modelo Usuario

Revision ID: 2d61561695fa
Revises: f4a74ce3d727
Create Date: 2025-01-27 10:56:00.978412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d61561695fa'
down_revision = 'f4a74ce3d727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index('idx_localidad_empresa')
        batch_op.drop_index('idx_nombre_empresa')

    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_index('idx_localidad_trabajador')
        batch_op.drop_index('idx_nombre_trabajador')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.create_index('idx_nombre_trabajador', ['nombre'], unique=False)
        batch_op.create_index('idx_localidad_trabajador', ['localidad'], unique=False)

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index('idx_nombre_empresa', ['nombre'], unique=False)
        batch_op.create_index('idx_localidad_empresa', ['localidad'], unique=False)

    op.drop_table('usuarios')
    # ### end Alembic commands ###
