"""Creación de la tabla Trabajador

Revision ID: 41856cee6d2b
Revises: 
Create Date: 2025-01-27 08:57:09.129605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41856cee6d2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=50), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('localidad', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajador')
    # ### end Alembic commands ###
