"""Creación de tabla requisitos_empresa

Revision ID: 7f85993db039
Revises: bb1c209147d8
Create Date: 2025-02-05 11:39:51.549041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f85993db039'
down_revision = 'bb1c209147d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisitos_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre_requisito', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisitos_empresa')
    # ### end Alembic commands ###
