"""Insert trabajadores activos en empresa

Revision ID: 80937afbbdf7
Revises: f96528bd3d75
Create Date: 2025-02-10 10:32:09.090721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80937afbbdf7'
down_revision = 'f96528bd3d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_trabajadores', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('n_trabajadores')

    # ### end Alembic commands ###
