"""Renombrar columna tipo a categoria en documentos

Revision ID: b733c9b6014c
Revises: 088f20761db6
Create Date: 2025-02-03 12:34:49.228409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b733c9b6014c'
down_revision = '088f20761db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_column('fecha_vencimiento')

    # ### end Alembic commands ###
