"""Agregar columna apellido y empresa a Trabajador

Revision ID: bb1c209147d8
Revises: b733c9b6014c
Create Date: 2025-02-04 08:47:42.209075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1c209147d8'
down_revision = 'b733c9b6014c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('empresa', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_column('empresa')
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
