"""Agregando columna tipo a trabajadores

Revision ID: dd1730a68934
Revises: 2d61561695fa
Create Date: 2025-01-29 23:40:48.123860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1730a68934'
down_revision = '2d61561695fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
