"""Cambio de mail a email

Revision ID: e33c8fb3b40f
Revises: e530c63b7537
Create Date: 2025-02-11 11:35:35.777169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e33c8fb3b40f'
down_revision = 'e530c63b7537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.drop_column('mail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
