"""Agregar campo tipo a RequisitoEmpresa

Revision ID: fcd7b680e299
Revises: 7e22e5231558
Create Date: 2025-02-12 17:08:28.237658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcd7b680e299'
down_revision = '7e22e5231558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitos_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=255), nullable=False))
        batch_op.drop_column('nombre_requisito')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitos_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_requisito', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
